Algoritmo "Cálculo da área de um quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edgar Natanael
// Descrição   : Calcular a área do quadrado(função)
// Aluno(a)    : Esley
// Data atual  : 27/03/2023

var
   lado, area: real

Inicio
   escreva("Digite o valor do lado do quadrado: ")
   leia(lado)

   area <- lado * lado

   escreva("A área do quadrado é: ", area)
FimAlgoritmo








